### ISSUE TITLE
Float menu visible after click on category.

### ISSUE THREAD

**Issue by thghca** [FluffierThanThou/RW_ArchitectSense#12]
RW_ArchitectSense/Source/ArchitectSense/Designator_SubCategory.cs
`
Find.WindowStack.FloatMenu?.Close(false);
SelectedItem.ProcessInput(ev);
`
 I think this lines should be swapped.

**Comment by notfood** [comment]
Oops. Didn't know my forced commits would appear here... I don't see how to delete those. Only the last one is valid.

It targets the same issue. I noticed that the patch THG made didn't work for the situations where materials aren't available. The one in HardcoreSK required harmony patches and it wasn't for my liking either. So here is another take to the issue.
