### ISSUE TITLE
Hide Categories

### ISSUE THREAD

**Issue by Richetoku** [FluffierThanThou/RW_ArchitectSense#6]
I am new to modding and I made a mod for personal use to move mod items to another category under a subcategory using architect sense. Now that the original category is empty, I do not know how to hide the original. Is there an option that I can use to hide the category or can Architect Sense automatically hide a category if it is empty.
I did this to mods like Vegetable Garden to put the brewery stuff in a sub category under production, and some other mods in a similar way.
I tried patching to remove the original category, but then Architect Sense does not find them and the items are just hidden. The debug for the subcategory says "did not have any (resolved) contents! Skipping."

**Comment by FluffierThanThou** [comment]
You can do it with a dll mod, but I suppose I really should make this accessible from xml.

If you're willing and able to add a C# assembly (so a dll), you'll find the tools to do this in the ArchitectSense.DesignatorUtilities class.

**Comment by Richetoku** [comment]
I figured out how to do it using a xml patch to change all the categories for the items and their parent nodes to one of the main categories and then changing the category to a null node. That works. I tried removing the categories first, but that gave an error that the designator xml was empty.

**Comment by FluffierThanThou** [comment]
yeah, that would work. It's not really a nice solution though, so I'm still going to try and make a better solution possible.

Glad you got something worked out in the mean time though, means I don't have to rush ;)

**Comment by FluffierThanThou** [comment]
I've added two defs; `RemoveCategory` and `MergeCategories`. They're simple, and do what they suggest they do. See the examples folder for an example on how (not) to use them.
